# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0002_auto_20170329_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaner',
            old_name='city',
            new_name='cities',
        ),
    ]
