# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0003_auto_20170329_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='email',
            field=models.EmailField(default='qq@qq.qq', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='cities',
            field=models.ManyToManyField(to='cities.City'),
        ),
    ]
