# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cleaner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='cleaners.Cleaner'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='customers.Customer'),
        ),
    ]
